// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClApGMFvAqURc0O1XxdZROQBksWoB95wM',
    appId: '1:639858293131:web:37d4050e9cfe94e856978e',
    messagingSenderId: '639858293131',
    projectId: 'studypair-c081b',
    authDomain: 'studypair-c081b.firebaseapp.com',
    storageBucket: 'studypair-c081b.firebasestorage.app',
    measurementId: 'G-WZ1716Q1P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWA5h46x0_gmukVRKwlGRcRY7tub9p8KA',
    appId: '1:639858293131:android:aab40b9449baa9c256978e',
    messagingSenderId: '639858293131',
    projectId: 'studypair-c081b',
    storageBucket: 'studypair-c081b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG-uoDpv_m2YLwkmuFngv4l8s6B7SCdYw',
    appId: '1:639858293131:ios:0e9f244c0a74373656978e',
    messagingSenderId: '639858293131',
    projectId: 'studypair-c081b',
    storageBucket: 'studypair-c081b.firebasestorage.app',
    iosBundleId: 'com.example.studyPair',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG-uoDpv_m2YLwkmuFngv4l8s6B7SCdYw',
    appId: '1:639858293131:ios:0e9f244c0a74373656978e',
    messagingSenderId: '639858293131',
    projectId: 'studypair-c081b',
    storageBucket: 'studypair-c081b.firebasestorage.app',
    iosBundleId: 'com.example.studyPair',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClApGMFvAqURc0O1XxdZROQBksWoB95wM',
    appId: '1:639858293131:web:722308c4ecb11e1456978e',
    messagingSenderId: '639858293131',
    projectId: 'studypair-c081b',
    authDomain: 'studypair-c081b.firebaseapp.com',
    storageBucket: 'studypair-c081b.firebasestorage.app',
    measurementId: 'G-7P44LYTRDJ',
  );
}
